### ISSUE TITLE
The Inaugural Issue! (color scheme choices/bugs :)

### ISSUE THREAD

**Issue by baurigae** [Zeioth/atom-visual-studio-code-light-ui#1]
I like your theme very much, and, as I'm "in the market" :) for a light UI theme for Atom but can't quite make one myself.. I'm very grateful for your effort. 

And I have two questions: first, can the accent color on the active tab (left border, inherited, I take it, from One Light) be changed to be the same _blue_ hue that you have in the status bar, or indeed, to any color; and second, is this

![screenshot from 2015-10-22 22 49 24](https://cloud.githubusercontent.com/assets/5447269/10711733/174f7ce0-7a85-11e5-8196-f4bcc0f9d21c.png)

... a bug or a feature? I mean the background color for the find/replace panel?

Thanks!

**Comment by Zeioth** [comment]
Indeed it is a bug. I'm going to commit an update in a couple of minutes for both themes. By the way, could you please tell me to what packages correspond the elements I mark in the image? I'd like to correct them too.

The element you refer is dependant of your syntax color. If you want to set a different color you can write this in your styles.less file

```
 .theme-atom-visual-studio-code-light-ui {
   .tab-bar .tab::before {
     background: #007ACC;
   }
}
```

![a](https://cloud.githubusercontent.com/assets/3357792/10712471/8a23194a-7a9c-11e5-9eec-71aed8fb4783.png)

**Comment by baurigae** [comment]
Thanks a lot!
and well the packages are `terminal-panel`, and, `wordcount`
https://github.com/thedaniel/terminal-panel
https://github.com/nesQuick/atom-wordcount

I'm really a bad bug reporter, I should have said immediately: I'm running Atom 1.0.19, on Ubuntu 15.04

**Comment by Zeioth** [comment]
Added integration for terminal-panel and atom-wordcount in both themes. If you find any other package showing incorrectly please, tell me. Thank you for report!
